// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AIScore struct {
	Overall        float64  `json:"overall"`
	Insights       *string  `json:"insights,omitempty"`
	Strengths      []string `json:"strengths,omitempty"`
	Concerns       []string `json:"concerns,omitempty"`
	Recommendation string   `json:"recommendation"`
	GeneratedAt    string   `json:"generatedAt"`
}

type Application struct {
	ID                string             `json:"id"`
	Job               *Job               `json:"job"`
	Candidate         *Candidate         `json:"candidate"`
	Status            string             `json:"status"`
	AppliedDate       string             `json:"appliedDate"`
	LastUpdated       string             `json:"lastUpdated"`
	ResumeURL         *string            `json:"resumeUrl,omitempty"`
	CoverLetter       *string            `json:"coverLetter,omitempty"`
	LinkedinURL       *string            `json:"linkedinUrl,omitempty"`
	PortfolioURL      *string            `json:"portfolioUrl,omitempty"`
	YearsOfExperience *int               `json:"yearsOfExperience,omitempty"`
	CurrentLocation   *string            `json:"currentLocation,omitempty"`
	WillingToRelocate *bool              `json:"willingToRelocate,omitempty"`
	ExpectedSalary    *float64           `json:"expectedSalary,omitempty"`
	Availability      *string            `json:"availability,omitempty"`
	AiScore           *AIScore           `json:"aiScore,omitempty"`
	Notes             []*ApplicationNote `json:"notes,omitempty"`
	Timeline          []*TimelineEvent   `json:"timeline,omitempty"`
}

type ApplicationFilters struct {
	JobID    *string  `json:"jobId,omitempty"`
	Status   *string  `json:"status,omitempty"`
	DateFrom *string  `json:"dateFrom,omitempty"`
	DateTo   *string  `json:"dateTo,omitempty"`
	MinScore *float64 `json:"minScore,omitempty"`
}

type ApplicationInput struct {
	JobID             string   `json:"jobId"`
	FirstName         string   `json:"firstName"`
	LastName          string   `json:"lastName"`
	Email             string   `json:"email"`
	Phone             *string  `json:"phone,omitempty"`
	ResumeURL         *string  `json:"resumeUrl,omitempty"`
	CoverLetter       *string  `json:"coverLetter,omitempty"`
	LinkedinURL       *string  `json:"linkedinUrl,omitempty"`
	PortfolioURL      *string  `json:"portfolioUrl,omitempty"`
	YearsOfExperience *int     `json:"yearsOfExperience,omitempty"`
	CurrentLocation   *string  `json:"currentLocation,omitempty"`
	WillingToRelocate *bool    `json:"willingToRelocate,omitempty"`
	ExpectedSalary    *float64 `json:"expectedSalary,omitempty"`
	Availability      *string  `json:"availability,omitempty"`
}

type ApplicationNote struct {
	ID         string `json:"id"`
	Author     *User  `json:"author"`
	Content    string `json:"content"`
	CreatedAt  string `json:"createdAt"`
	IsInternal bool   `json:"isInternal"`
}

type Candidate struct {
	ID                 string            `json:"id"`
	FirstName          string            `json:"firstName"`
	LastName           string            `json:"lastName"`
	Email              string            `json:"email"`
	Phone              *string           `json:"phone,omitempty"`
	Location           *string           `json:"location,omitempty"`
	Headline           *string           `json:"headline,omitempty"`
	Summary            *string           `json:"summary,omitempty"`
	ResumeURL          *string           `json:"resumeUrl,omitempty"`
	LinkedinURL        *string           `json:"linkedinUrl,omitempty"`
	PortfolioURL       *string           `json:"portfolioUrl,omitempty"`
	GithubURL          *string           `json:"githubUrl,omitempty"`
	Skills             []string          `json:"skills,omitempty"`
	Experience         []*WorkExperience `json:"experience,omitempty"`
	Education          []*Education      `json:"education,omitempty"`
	Certifications     []*Certification  `json:"certifications,omitempty"`
	Languages          []*Language       `json:"languages,omitempty"`
	Applications       []*Application    `json:"applications,omitempty"`
	Availability       *string           `json:"availability,omitempty"`
	ExpectedSalary     *float64          `json:"expectedSalary,omitempty"`
	PreferredLocations []string          `json:"preferredLocations,omitempty"`
	RemotePreference   *string           `json:"remotePreference,omitempty"`
	CreatedAt          string            `json:"createdAt"`
	UpdatedAt          string            `json:"updatedAt"`
}

type CandidateProfileInput struct {
	FirstName          *string  `json:"firstName,omitempty"`
	LastName           *string  `json:"lastName,omitempty"`
	Email              *string  `json:"email,omitempty"`
	Phone              *string  `json:"phone,omitempty"`
	Location           *string  `json:"location,omitempty"`
	Headline           *string  `json:"headline,omitempty"`
	Summary            *string  `json:"summary,omitempty"`
	LinkedinURL        *string  `json:"linkedinUrl,omitempty"`
	PortfolioURL       *string  `json:"portfolioUrl,omitempty"`
	GithubURL          *string  `json:"githubUrl,omitempty"`
	Skills             []string `json:"skills,omitempty"`
	Availability       *string  `json:"availability,omitempty"`
	ExpectedSalary     *float64 `json:"expectedSalary,omitempty"`
	PreferredLocations []string `json:"preferredLocations,omitempty"`
	RemotePreference   *string  `json:"remotePreference,omitempty"`
}

type Certification struct {
	Name         string  `json:"name"`
	Issuer       string  `json:"issuer"`
	IssueDate    string  `json:"issueDate"`
	ExpiryDate   *string `json:"expiryDate,omitempty"`
	CredentialID *string `json:"credentialId,omitempty"`
}

type ConversionRates struct {
	ViewToApply       float64 `json:"viewToApply"`
	ApplyToScreen     float64 `json:"applyToScreen"`
	ScreenToInterview float64 `json:"screenToInterview"`
	InterviewToOffer  float64 `json:"interviewToOffer"`
	OfferToAccept     float64 `json:"offerToAccept"`
}

type DateRangeInput struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type Education struct {
	Institution string   `json:"institution"`
	Degree      string   `json:"degree"`
	Field       string   `json:"field"`
	StartDate   string   `json:"startDate"`
	EndDate     *string  `json:"endDate,omitempty"`
	Gpa         *float64 `json:"gpa,omitempty"`
}

type Job struct {
	ID               string       `json:"id"`
	Title            string       `json:"title"`
	Department       string       `json:"department"`
	Location         string       `json:"location"`
	EmploymentType   string       `json:"employmentType"`
	ExperienceLevel  *string      `json:"experienceLevel,omitempty"`
	SalaryRange      *SalaryRange `json:"salaryRange,omitempty"`
	Description      *string      `json:"description,omitempty"`
	Requirements     *string      `json:"requirements,omitempty"`
	Responsibilities *string      `json:"responsibilities,omitempty"`
	Benefits         *string      `json:"benefits,omitempty"`
	Skills           []string     `json:"skills,omitempty"`
	Status           string       `json:"status"`
	PostedDate       *string      `json:"postedDate,omitempty"`
	ClosingDate      *string      `json:"closingDate,omitempty"`
	ApplicationCount int          `json:"applicationCount"`
	ViewCount        int          `json:"viewCount"`
	RemoteWork       *bool        `json:"remoteWork,omitempty"`
	UrgentHiring     *bool        `json:"urgentHiring,omitempty"`
	CreatedBy        *User        `json:"createdBy,omitempty"`
	CreatedAt        string       `json:"createdAt"`
	UpdatedAt        string       `json:"updatedAt"`
}

type JobDescriptionInput struct {
	Title               string   `json:"title"`
	Department          string   `json:"department"`
	ExperienceLevel     string   `json:"experienceLevel"`
	KeyResponsibilities []string `json:"keyResponsibilities,omitempty"`
	RequiredSkills      []string `json:"requiredSkills,omitempty"`
}

type JobDescriptionOutput struct {
	Description      string   `json:"description"`
	Requirements     string   `json:"requirements"`
	Responsibilities string   `json:"responsibilities"`
	SuggestedSkills  []string `json:"suggestedSkills"`
}

type JobFilters struct {
	Department      *string `json:"department,omitempty"`
	Status          *string `json:"status,omitempty"`
	EmploymentType  *string `json:"employmentType,omitempty"`
	RemoteWork      *bool   `json:"remoteWork,omitempty"`
	ExperienceLevel *string `json:"experienceLevel,omitempty"`
	Location        *string `json:"location,omitempty"`
}

type JobInput struct {
	Title            string   `json:"title"`
	Department       string   `json:"department"`
	Location         string   `json:"location"`
	EmploymentType   string   `json:"employmentType"`
	ExperienceLevel  *string  `json:"experienceLevel,omitempty"`
	SalaryMin        *float64 `json:"salaryMin,omitempty"`
	SalaryMax        *float64 `json:"salaryMax,omitempty"`
	SalaryCurrency   *string  `json:"salaryCurrency,omitempty"`
	Description      *string  `json:"description,omitempty"`
	Requirements     *string  `json:"requirements,omitempty"`
	Responsibilities *string  `json:"responsibilities,omitempty"`
	Benefits         *string  `json:"benefits,omitempty"`
	Skills           []string `json:"skills,omitempty"`
	RemoteWork       *bool    `json:"remoteWork,omitempty"`
	UrgentHiring     *bool    `json:"urgentHiring,omitempty"`
}

type JobPerformance struct {
	Job            *Job     `json:"job"`
	Views          int      `json:"views"`
	Applications   int      `json:"applications"`
	ConversionRate float64  `json:"conversionRate"`
	AvgTimeToFill  *float64 `json:"avgTimeToFill,omitempty"`
}

type Language struct {
	Language    string `json:"language"`
	Proficiency string `json:"proficiency"`
}

type Mutation struct {
}

type PipelineStage struct {
	Status       string         `json:"status"`
	Count        int            `json:"count"`
	Applications []*Application `json:"applications"`
}

type Query struct {
}

type RecruitmentMetrics struct {
	TotalJobs             int                `json:"totalJobs"`
	ActiveJobs            int                `json:"activeJobs"`
	TotalApplications     int                `json:"totalApplications"`
	AvgApplicationsPerJob float64            `json:"avgApplicationsPerJob"`
	AvgTimeToHire         *float64           `json:"avgTimeToHire,omitempty"`
	ConversionRates       *ConversionRates   `json:"conversionRates,omitempty"`
	TopPerformingJobs     []*JobPerformance  `json:"topPerformingJobs,omitempty"`
	ApplicationsByStatus  []*StatusBreakdown `json:"applicationsByStatus,omitempty"`
	ApplicationTrend      []*TrendPoint      `json:"applicationTrend,omitempty"`
	SourceBreakdown       []*SourceBreakdown `json:"sourceBreakdown,omitempty"`
}

type SalaryRange struct {
	Min      *float64 `json:"min,omitempty"`
	Max      *float64 `json:"max,omitempty"`
	Currency *string  `json:"currency,omitempty"`
}

type SourceBreakdown struct {
	Source     string  `json:"source"`
	Count      int     `json:"count"`
	Percentage float64 `json:"percentage"`
}

type StatusBreakdown struct {
	Status     string  `json:"status"`
	Count      int     `json:"count"`
	Percentage float64 `json:"percentage"`
}

type TimelineEvent struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	PerformedBy *User  `json:"performedBy,omitempty"`
	Timestamp   string `json:"timestamp"`
}

type TrendPoint struct {
	Date  string `json:"date"`
	Value int    `json:"value"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
}

type WorkExperience struct {
	Company      string   `json:"company"`
	Title        string   `json:"title"`
	StartDate    string   `json:"startDate"`
	EndDate      *string  `json:"endDate,omitempty"`
	Current      bool     `json:"current"`
	Description  *string  `json:"description,omitempty"`
	Achievements []string `json:"achievements,omitempty"`
}

type ApplicationStatus string

const (
	ApplicationStatusNew                ApplicationStatus = "NEW"
	ApplicationStatusScreening          ApplicationStatus = "SCREENING"
	ApplicationStatusPhoneScreen        ApplicationStatus = "PHONE_SCREEN"
	ApplicationStatusTechnicalInterview ApplicationStatus = "TECHNICAL_INTERVIEW"
	ApplicationStatusOnsiteInterview    ApplicationStatus = "ONSITE_INTERVIEW"
	ApplicationStatusOffer              ApplicationStatus = "OFFER"
	ApplicationStatusAccepted           ApplicationStatus = "ACCEPTED"
	ApplicationStatusRejected           ApplicationStatus = "REJECTED"
	ApplicationStatusWithdrawn          ApplicationStatus = "WITHDRAWN"
)

var AllApplicationStatus = []ApplicationStatus{
	ApplicationStatusNew,
	ApplicationStatusScreening,
	ApplicationStatusPhoneScreen,
	ApplicationStatusTechnicalInterview,
	ApplicationStatusOnsiteInterview,
	ApplicationStatusOffer,
	ApplicationStatusAccepted,
	ApplicationStatusRejected,
	ApplicationStatusWithdrawn,
}

func (e ApplicationStatus) IsValid() bool {
	switch e {
	case ApplicationStatusNew, ApplicationStatusScreening, ApplicationStatusPhoneScreen, ApplicationStatusTechnicalInterview, ApplicationStatusOnsiteInterview, ApplicationStatusOffer, ApplicationStatusAccepted, ApplicationStatusRejected, ApplicationStatusWithdrawn:
		return true
	}
	return false
}

func (e ApplicationStatus) String() string {
	return string(e)
}

func (e *ApplicationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApplicationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApplicationStatus", str)
	}
	return nil
}

func (e ApplicationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApplicationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApplicationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EmploymentType string

const (
	EmploymentTypeFullTime   EmploymentType = "FULL_TIME"
	EmploymentTypePartTime   EmploymentType = "PART_TIME"
	EmploymentTypeContract   EmploymentType = "CONTRACT"
	EmploymentTypeTemporary  EmploymentType = "TEMPORARY"
	EmploymentTypeInternship EmploymentType = "INTERNSHIP"
)

var AllEmploymentType = []EmploymentType{
	EmploymentTypeFullTime,
	EmploymentTypePartTime,
	EmploymentTypeContract,
	EmploymentTypeTemporary,
	EmploymentTypeInternship,
}

func (e EmploymentType) IsValid() bool {
	switch e {
	case EmploymentTypeFullTime, EmploymentTypePartTime, EmploymentTypeContract, EmploymentTypeTemporary, EmploymentTypeInternship:
		return true
	}
	return false
}

func (e EmploymentType) String() string {
	return string(e)
}

func (e *EmploymentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmploymentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmploymentType", str)
	}
	return nil
}

func (e EmploymentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EmploymentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EmploymentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExperienceLevel string

const (
	ExperienceLevelEntry     ExperienceLevel = "ENTRY"
	ExperienceLevelJunior    ExperienceLevel = "JUNIOR"
	ExperienceLevelMid       ExperienceLevel = "MID"
	ExperienceLevelSenior    ExperienceLevel = "SENIOR"
	ExperienceLevelLead      ExperienceLevel = "LEAD"
	ExperienceLevelPrincipal ExperienceLevel = "PRINCIPAL"
)

var AllExperienceLevel = []ExperienceLevel{
	ExperienceLevelEntry,
	ExperienceLevelJunior,
	ExperienceLevelMid,
	ExperienceLevelSenior,
	ExperienceLevelLead,
	ExperienceLevelPrincipal,
}

func (e ExperienceLevel) IsValid() bool {
	switch e {
	case ExperienceLevelEntry, ExperienceLevelJunior, ExperienceLevelMid, ExperienceLevelSenior, ExperienceLevelLead, ExperienceLevelPrincipal:
		return true
	}
	return false
}

func (e ExperienceLevel) String() string {
	return string(e)
}

func (e *ExperienceLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExperienceLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExperienceLevel", str)
	}
	return nil
}

func (e ExperienceLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExperienceLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExperienceLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStatus string

const (
	JobStatusDraft     JobStatus = "DRAFT"
	JobStatusPublished JobStatus = "PUBLISHED"
	JobStatusClosed    JobStatus = "CLOSED"
	JobStatusArchived  JobStatus = "ARCHIVED"
)

var AllJobStatus = []JobStatus{
	JobStatusDraft,
	JobStatusPublished,
	JobStatusClosed,
	JobStatusArchived,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusDraft, JobStatusPublished, JobStatusClosed, JobStatusArchived:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RemoteWorkType string

const (
	RemoteWorkTypeOnsite RemoteWorkType = "ONSITE"
	RemoteWorkTypeRemote RemoteWorkType = "REMOTE"
	RemoteWorkTypeHybrid RemoteWorkType = "HYBRID"
)

var AllRemoteWorkType = []RemoteWorkType{
	RemoteWorkTypeOnsite,
	RemoteWorkTypeRemote,
	RemoteWorkTypeHybrid,
}

func (e RemoteWorkType) IsValid() bool {
	switch e {
	case RemoteWorkTypeOnsite, RemoteWorkTypeRemote, RemoteWorkTypeHybrid:
		return true
	}
	return false
}

func (e RemoteWorkType) String() string {
	return string(e)
}

func (e *RemoteWorkType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RemoteWorkType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RemoteWorkType", str)
	}
	return nil
}

func (e RemoteWorkType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RemoteWorkType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RemoteWorkType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
